default:
  tags:
    - docker
  image: archlinux:base

before_script:
  - pacman -Syu --noconfirm
    boost
    boost-libs
    cmake
    gcc
    gcovr
    grep
    intel-tbb
    ninja
    opencv
    wget

build:
  stage: build
  script:
    - mkdir build/
    - cd build/
    - export CXXFLAGS=--coverage
    - cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug
    - cmake --build .
  artifacts:
    untracked: true

test:
  stage: test
  script:
    - (! ./build/pav1iet)
    - (! ./build/pav1iet does-not-exist)
    - ./build/pav1iet -h
    - ./build/pav1iet -v
    - (! ./build/pav1iet <(echo invalid annotations))
    - (! echo invalid input | ./build/pav1iet -)
    - ./examples/prepare_INRIA_person_dataset.sh
    - test $(grep 'Bounding box' ./INRIAPerson/Train/annotations/*.txt | wc -l) -eq 1237
    - ./build/pav1iet ./INRIAPerson/Train-pos.lst -o 'train-%04i.png'
    - test $(ls train-*.png | wc -l) -eq 1237
    - test $(grep 'Bounding box' ./INRIAPerson/Test/annotations/*.txt | wc -l) -eq 589
    - ./build/pav1iet ./INRIAPerson/Test-pos.lst -o 'test-%03i.png'
    - test $(ls test-*.png | wc -l) -eq 589
    - cd build/
    - mkdir coverage/
    - gcovr -r ..
      -j$(nproc)
      -s
      --filter ../src
      --html --html-title pav1iet --html-details
      -o coverage/report.html
  coverage: '/lines:\s+(\d+\.\d+|\d+)%/'
  artifacts:
    paths:
      - build/coverage/
