name: Linux

on: [push, pull_request]

jobs:
  build:
    name: GCC-${{matrix.build_type}}
    runs-on: ubuntu-22.04
    container: ubuntu:24.04
    strategy:
      fail-fast: true
      matrix:
          build_type: [Release, Debug]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Dependencies
      run: |
        apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --no-install-suggests \
          bash \
          build-essential \
          cmake \
          grep \
          libboost-dev \
          libboost-program-options-dev \
          libopencv-dev \
          libopencv-imgcodecs-dev \
          libopencv-imgproc-dev \
          libtbb-dev \
          ninja-build \
          wget

    - name: Setup Coverage Dependencies
      if: ${{matrix.build_type == 'Debug'}}
      run: |
        DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --no-install-suggests \
          gcovr \
          git \
          gpg \
          gpg-agent

    - name: Setup Debug Environment
      if: ${{matrix.build_type == 'Debug'}}
      run: |
        echo 'CXXFLAGS=--coverage' >> $GITHUB_ENV

    - name: Configure
      run: |
        cmake -S . -B build_${{matrix.build_type}} -G Ninja

    - name: Build
      run: |
        cmake --build build_${{matrix.build_type}} \
              --config ${{matrix.build_type}}

    - name: Test
      shell: bash
      run: |
        ! ./build_${{matrix.build_type}}/pav1iet
        ! ./build_${{matrix.build_type}}/pav1iet does-not-exist
        ./build_${{matrix.build_type}}/pav1iet -h
        ./build_${{matrix.build_type}}/pav1iet -v
        ! ./build_${{matrix.build_type}}/pav1iet <(echo invalid annotations)
        ! echo invalid input | ./build_${{matrix.build_type}}/pav1iet -
        ./examples/prepare_INRIA_person_dataset.sh
        test $(grep 'Bounding box' ./INRIAPerson/Train/annotations/*.txt | wc -l) -eq 1237
        ./build_${{matrix.build_type}}/pav1iet ./INRIAPerson/Train-pos.lst -o 'train-%04i.png'
        test $(ls train-*.png | wc -l) -eq 1237
        test $(grep 'Bounding box' ./INRIAPerson/Test/annotations/*.txt | wc -l) -eq 589
        ./build_${{matrix.build_type}}/pav1iet ./INRIAPerson/Test-pos.lst -o 'test-%03i.png'
        test $(ls test-*.png | wc -l) -eq 589

    - name: Generate Coverage
      if: matrix.build_type == 'Debug'
      run: |
        cd build_${{matrix.build_type}}
        gcovr -r .. . -s --cobertura coverage.xml

    - name: Upload Coverage to Codecov
      if: ${{ startswith(matrix.build_type, 'Debug') }}
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true
